## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:

    
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: dikshi1797@gmail.com
    password: vwiqtpokkynwhkkc
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false






  queries:
    users-query: select email, password, active from users where email=?
    roles-query: select email, role from users where email=?
server:
  servlet:
    contextPath: /api

jwtSecret: me.zhulin
jwtExpiration: 86400


  